### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by davidhendrickmb** [tekmaven/nClam#30]
Hi there,
I was wondering if the request to Clam AV is in any way secured via SSL or TLS or if its possible to configure this?

Thanks,
David

**Comment by wscalf** [comment]
I don't think so, at least not on its own, but with a little effort most things are possible. I'm looking to do exactly this, and I have a rough idea that might work
* Set up a Nginx as a _layer 4_ (not HTTP) reverse proxy
* Hope I can enable TLS-termination even though it's not HTTP, giving TLS in and a clear channel through to ClamAV

Then on my client
* Open a TcpClient to the reverse proxy
* Get its network stream
* Wrap it in an SslStream
* Do the client handshake
* Pass the SslStream off to NClam, which it then uses as a normal channel to talk to ClamAV, but it's transparently encrypted from this node to the node running Clam and the reverse proxy

Though at the moment, NClam doesn't appear to accept an arbitrary stream. I'm wondering if the maintainers would be open to a pull request to open that up.

**Comment by wscalf** [comment]
Confirmed. This _can_ work - I have a super rough implementation working locally with a fork/PR/PoC coming after I get a chance to do some cleanup.

**Comment by wscalf** [comment]
Okay, the PR is here: https://github.com/tekmaven/nClam/pull/33

The way I solved this was with an application connecting through a reverse proxy to get to clamd. You can think of the reverse proxy as being like an ingress controller (or otherwise just an ingress point) on a host of some kind - in this case, I'm using docker and docker-compose, but Kubernetes or some other orchestrator (or a VM deployment) could get you there as well. The important thing is that external callers don't talk to clam - they talk to the reverse proxy.

You'll need some things to follow along-
* Docker
* Docker Compose
* An SSL certificate your computer considers valid (this can be a self-signed test cert, but you do have to trust its public key - this can be done by adding it to the Trusted People store on Windows, for example.) For simplicity, I'll be using the basic crt and key files generated with openssl, which aren't encrypted or meant for production use. Before considering a production deployment, look into options for certificate management with nginx.

Once you have those, you need an nginx config file. Here's the one I used, plus some comments:
```
worker_processes 1;

events { worker_connections 1024; }

stream { #layer-4 proxy
    upstream clamav { #defines the back-end for the proxy - the clamav.local service described in the docker-compose file
            server clamav.local:3310;
    }

    server {
        listen  3310 ssl; #listen on clamavd's port and enable TLS
        proxy_pass clamav; #forward traffic received on this port to the clamav backend, after handling TLS

        ssl_certificate        /etc/ssl/certs/server.crt; #the public certificate to use for TLS, loaded from the cert folder in docker-compose
        ssl_certificate_key    /etc/ssl/certs/server.key; #the private key for the certificate for TLS, loaded from the cert folder in docker-compose. 
        #Note: this key is NOT ENCRYPTED - Nginx has some support for managing private keys better than this. Look into that before deploying to production.
        ssl_protocols          TLSv1.2 TLSv1.3; #Only allow recent TLS versions
                                                #protocols and cipher suites are pretty configurable, but I was aiming to keep this example simple
    }
}
```

And a docker-compose file to tell it which services to create and how:
```
version: '2'
services:
  reverse-proxy:
    image: "nginx" #default nginx image
    ports:
      - "3310:3310" #clamd's port
    volumes:
      - "./cert:/etc/ssl/certs" #My certificate is made up of 'server.crt' and 'server.key' files in a 'cert' folder - this mounts them where nginx can find them
      - "./nginx.conf:/etc/nginx/nginx.conf" #my nginx.conf from above
  clamav.local:
    image: "dinkel/clamavd" #any clam image will do
```

And finally, run `docker-compose up` to download/install/configure nginx and clamav on a virtual network, which gives you the ability to create a secure connection on port 3310 and talk to clam as-normal. Now, to do that, we need to inherit from the usual ClamClient class and override the new virtual method made by my pull request above, creating something like this:

```
public class SecureClamClient : ClamClient
{
   public SecureClamClient(string server, int port = 3310) : base(server, port)
   {
   }
   protected override async Task<Stream> CreateConnection(TcpClient client)
   {
      var stream = await base.CreateConnection(client); //Get the normal stream from the base class
      var secureStream = new SslStream(stream, leaveInnerStreamOpen: false); //Wrap it in a TLS-aware stream

      //Does the TLS handshake with the reverse proxy, setting up a secure channel and forcing the server to prove its identity
      //Could also implement client certificate authentication between client and reverse proxy here to lock clamav down to authorized clients
      await secureStream.AuthenticateAsClientAsync(Server); 

      return secureStream; //Give the secure channel back to nClam which will use it as a regular old stream. 
      //Because the reverse proxy on the other end terminates TLS, the clamd server also won't know the difference.
   }
}
```
And then it should work as normal when talking to the virtual network created by docker-compose above. ..I realize this is kind of a lot, _but_ I think it solves the problem in a comprehensive way and doesn't add anything a modern container deployment wouldn't already be using.

**Comment by tekmaven** [comment]
This PR is merged!  Thanks!
